---
title: "MATH 3900: Mathematics Seminar - Mathematics of Climate"
tbl-colwidths: [5,10,35,5,5,10,10]
---

This page contains an outline of the topics, content, and assignments for the semester. Note that this schedule will be updated as the semester progresses, with all changes documented here.

::: column-screen-inset-right
+-----------------------+-------------------------------+--------------------------------------------------+--------+--------------------------------------------------------------------------------------------------------+-------------------------+---------+
| Week                  | Date                          | Topic                                            | Slides | Activity                                                                                               | Homework & Reading      | Project |
+:=====================:+===============================+==================================================+:======:+:======================================================================================================:+:=======================:+:=======:+
| [1](weeks/week-1.qmd) | Jan 23                        | Intro and Earth Balance Models                   |        | [📋](https://docs.google.com/document/d/1NwYQoeJXnzjYq2oUcTnepFX89SFwgO9tor0-lTuR5X4/edit?usp=sharing) | [✍](weeks/hws/hw-1.qmd) |         |
+-----------------------+-------------------------------+--------------------------------------------------+--------+--------------------------------------------------------------------------------------------------------+-------------------------+---------+
| [2](weeks/week-2.qmd) | Jan 30                        | Equilibria & Stability                           |        | [📋](weeks/week-2.qmd)                                                                                 | [✍](weeks/hws/hw-2.qmd) |         |
+-----------------------+-------------------------------+--------------------------------------------------+--------+--------------------------------------------------------------------------------------------------------+-------------------------+---------+
| [3](weeks/week-3.qmd) | Feb 6                         | Bifurcations                                     |        | [📋](weeks/week-3.qmd)                                                                                 | [✍](weeks/hws/hw-3.qmd) |         |
+-----------------------+-------------------------------+--------------------------------------------------+--------+--------------------------------------------------------------------------------------------------------+-------------------------+---------+
| [4](weeks/week-4.qmd) | Feb 13                        | Bifurcations                                     |        |                                                                                                        | [✍](weeks/hws/hw-4.qmd) |         |
|                       |                               |                                                  |        |                                                                                                        |                         |         |
|                       |                               | Discrete 1D Maps                                 |        |                                                                                                        |                         |         |
+-----------------------+-------------------------------+--------------------------------------------------+--------+--------------------------------------------------------------------------------------------------------+-------------------------+---------+
| [5](weeks/week-5.qmd) | Feb 20                        | 1D Chaos                                         |        | [📋](weeks/week-5.qmd)                                                                                 | [✍](weeks/hws/hw-5.qmd) |         |
+-----------------------+-------------------------------+--------------------------------------------------+--------+--------------------------------------------------------------------------------------------------------+-------------------------+---------+
| [6](weeks/week-6.qmd) | Feb 27                        | "Period 3 Implies Chaos" preparation             |        | [📋](weeks/week-6.qmd)                                                                                 | [✍](weeks/hws/hw-6.qmd) |         |
+-----------------------+-------------------------------+--------------------------------------------------+--------+--------------------------------------------------------------------------------------------------------+-------------------------+---------+
| 7                     | Mar 6                         | "Period 3 Implies Chaos"                         |        |                                                                                                        |                         |         |
+-----------------------+-------------------------------+--------------------------------------------------+--------+--------------------------------------------------------------------------------------------------------+-------------------------+---------+
| 8                     | Mar 20                        | Climate indices & Empirical Orthogonal Functions |        |                                                                                                        |                         |         |
+-----------------------+-------------------------------+--------------------------------------------------+--------+--------------------------------------------------------------------------------------------------------+-------------------------+---------+
| 9                     | Mar 27                        | Time Series Analysis                             |        |                                                                                                        |                         |         |
+-----------------------+-------------------------------+--------------------------------------------------+--------+--------------------------------------------------------------------------------------------------------+-------------------------+---------+
| 10                    | Apr 3                         | Extreme Value Theory                             |        |                                                                                                        |                         |         |
+-----------------------+-------------------------------+--------------------------------------------------+--------+--------------------------------------------------------------------------------------------------------+-------------------------+---------+
| 11                    | Apr 10                        | Attribution Theory, Work Time                    |        |                                                                                                        |                         |         |
+-----------------------+-------------------------------+--------------------------------------------------+--------+--------------------------------------------------------------------------------------------------------+-------------------------+---------+
| 12                    | Apr 17                        | Attribution Theory                               |        |                                                                                                        |                         |         |
+-----------------------+-------------------------------+--------------------------------------------------+--------+--------------------------------------------------------------------------------------------------------+-------------------------+---------+
| 13                    | Apr 24                        | Work Time, Final Presentation                    |        |                                                                                                        |                         |         |
|                       |                               |                                                  |        |                                                                                                        |                         |         |
|                       | 9:30 - 10:45                  |                                                  |        |                                                                                                        |                         |         |
+-----------------------+-------------------------------+--------------------------------------------------+--------+--------------------------------------------------------------------------------------------------------+-------------------------+---------+
| 14                    | May 1                         | Final Presentations                              |        |                                                                                                        |                         |         |
|                       |                               |                                                  |        |                                                                                                        |                         |         |
|                       | 9:30 - 10:45                  |                                                  |        |                                                                                                        |                         |         |
+-----------------------+-------------------------------+--------------------------------------------------+--------+--------------------------------------------------------------------------------------------------------+-------------------------+---------+
| Final                 | **Mon. May 12, 12:20 - 2:20** | Final Presentations                              |        |                                                                                                        |                         |         |
+-----------------------+-------------------------------+--------------------------------------------------+--------+--------------------------------------------------------------------------------------------------------+-------------------------+---------+
:::
