---
title: "HW 1: Energy Balance Models"
execute:
  freeze: auto
  echo: true
  eval: false
  warning: false
  message: false
---

::: callout-important
Due:

-   Friday, January 30, 9:30 AM
:::

# Introduction

WORDS

# Exercises

------------------------------------------------------------------------

### Exercise 1: Nighttime Temperature

Using Model 2 from class, estimate how much the atmosphere in the model would cool overnight. The heat capacity of the atmosphere is about $10^7$ J/(K$\cdot$ m$^2$).

(*Hint*: It's not much, so you can make some assumptions that make things easier! What radiation, if any, is coming into the top of the atmosphere? What radiation, if any, is going out? )

### Exercise 2: Budyko's Model

Satellite data suggests that blackbody radiation might not be the best model for Earth's outgoing radiation! Instead, we can use a linear(-ish) model: $A + BT_s$. (The ish is because $A$ and $B$ \textit{also} depend on temperature if we're being careful, as we'll consider in Parts (c) and (d).)

#### Part (a)

Modify Model 1 to use this form for Earth's outgoing radiation instead, and find an expression for surface temperature in this case. We'll call this temperature $T_0$.

#### Part (b)

Suppose that $S_0$ changes slightly by an amount we'll call $\Delta S$. If $\alpha, A,$ and $B$ don't change, write an expression for $\Delta T$, how much $T_s$ changes.

#### Part (c)

Suppose now that $\alpha$, $A$, and $B$ *do* change with temperature as follows: $$
    \begin{align*}
        \alpha(T) = \alpha_0 + \alpha_1 \Delta T; \\
        A(T) = A_0 + A_1 \Delta T; \\
        B(T) = B_0 + B_1 \Delta T;\\
    \end{align*}
$$\
where $\alpha_0, A_0, B_0$ are the values when $T = T_0$. Find an expression relating $\Delta S$ to $\Delta T$. You can assume that $(\Delta T)^2 \approx 0$.

#### Part (d)

With some wrangling of terms, you can get this to look like $$B_0 \Delta T = f (1- \alpha_0) \Delta S,$$ with $f$ condensing a pretty messy expression. Compare this to your answer to (b). Why do you think $f$ is called \`\`climate gain?"

### Exercise 3

READING QUESTION HERE
