---
title: "HW 4: 1D Discrete Maps"
execute:
  freeze: auto
  echo: true
  eval: false
  warning: false
  message: false
---

::: callout-important
Due:

-   Friday, February 20, 9:30 AM
:::

# Introduction

In class, we briefly looked at discrete one-dimensional maps written in terms of the difference in $x$, like $\Delta x = x$, where $\Delta x$ told us what to add to $x_n$ to get to $x_{n+1}$. For example, with this map, when we started with $x_0 = 1$, we found
$\begin{align*}
x_1 &= x_0 + \Delta x = 1 + 1 = 2, \\
x_2 &= x_1 + \Delta x = 2 + 2 = 4, \\
x_3 &= x_2 + \Delta x = 4 + 4 = 8,
$\begin{align*}
and so forth.

The more typical way to write these discrete 1D maps is in terms of $x_{n+1}$. So the map above, for instance, would be $x_{n+1} = 2x_n$.

We can still look for fixed points: values of $x_n$ such that $x_{n+1} = x_n$. We can also still look at their stability -- if we're just a little bit away from that fixed point value $x^*$, do we head towards $x^*$ (stable) or away (unstable)?

But compared to the continuous systems we've looked at previously, some more interesting behavior can arise. We can get **periodic** points, basically getting caught in a loop. For example, the map $x_{n+1} = -x_n^3$ has a pair of points of period 2: -1 and 1 keep flip-flopping.

# Exercises

------------------------------------------------------------------------

### Exercise 1: Exploring 1D maps

#### Part (a)

Choose three of the discrete 1D maps below. Find their equilibrium points and classify their stability.

-   $x_{n+1} = \sqrt{x_n}$
-   $x_{n+1} = x_n^3$
-   $x_{n+1} = x_n^2$
-   $x_{n+1} = \sin x$
-   $x_{n+1} = 3x_n - x_n^3$
-   $x_{n+1} = \ln x$
-   $x_{n+1} = \frac{2x_n}{1+x_n}$
-   $x_{n+1} = 3x_n - x_n^3$

#### Part (b)

For notation, much like in the continuous case, let $f(x_n)$ be the right side of the equation. In other words, $x_{n+1} = f(x_n)$.

For each equilibrium point $x^*$ that you found in Exercise 1, find the derivative $f'(x^*)$. What do you notice about this value and stability of $x^*$? Try to explain what's going on here.

### Exercise 2: Trajectories and Cobweb Diagrams

#### Part (a)

You'll keep working with the three maps you chose in Exercise 1 here. For each one, choose a few initial values $x_0$ (that are not a fixed point you found above) and calculate the next $x_n$ values from each of those initial points, until you feel like someone could see what's going on. What kinds of things do you notice about your map?

#### Part (b)
Now for each of your maps, do the following:

-   Draw a coordinate system with $x_n$ on the horizontal axis and $x_{n+1}$ on the vertical axis.
-   Draw the diagonal line $x_{n+1} = x_n$.
-   Draw the curve corresponding to that map. (For example, $x_{n+1} = 2x_n$ would be a straight line through the origin with slope 2.) I'll call this the graph of $f$ (where $x_{n+1} = f(x_n)$.)
-   For each of your initial values $x_0$, go to that point on the horizontal axis. Draw a line straight up/down until you hit the graph of $f$. Then move horizontally until you hit the $x_{n+1} = x_n$ line. Then move vertically to the graph of $f$ again, then horizontally to the diagonal line again, etc.

This graph is called a cobweb diagram. How does it show what's happening in your maps?

### Exercise 3: Periodic Points

Look for points of period 2 in your chosen maps. These should be points such that $x_{n+2} = x_n$ that are not your fixed points. If you don't think there are any, explain why.